import { createAction } from '@reduxjs/toolkit'

export const mouseMove = createAction('MOUSE_MOVE')
export const reset = createAction('RESET')
export const addNode = createAction('CREATE_NODE')
export const updateNode = createAction('UPDATE_NODE')
export const removeNode = createAction('DELETE_NODE')
export const addEdge = createAction('CREATE_EDGE')
export const updateEdge = createAction('UPDATE_EDGE')
export const removeEdge = createAction('DELETE_EDGE')
export const addLiteral = createAction('CREATE_LITERAL')
export const updateLiteral = createAction('UPDATE_LITERAL')
export const removeLiteral = createAction('DELETE_LITERAL')
export const toggleSelectedItems = createAction('TOGGLE_SELECTED_ITEMS')
export const setSelectedItems = createAction('SET_SELECTED_ITEMS')
export const setMovingEdge = createAction('SET_MOVING_EDGE')
export const setActiveIds = createAction('SET_ACTIVE_IDS')
export const updateGraphParameters = createAction('UPDATE_GRAPH_PARAMETERS')
