import { createAction } from '@reduxjs/toolkit'

export const mouseMove = createAction('MOUSE_MOVE')
export const reset = createAction('RESET')
export const addNode = createAction('ADD_NODE')
export const updateNode = createAction('UPDATE_NODE')
export const removeNode = createAction('REMOVE_NODE')
export const addEdge = createAction('ADD_EDGE')
export const updateEdge = createAction('UPDATE_EDGE')
export const removeEdge = createAction('REMOVE_EDGE')
export const addLiteral = createAction('ADD_LITERAL')
export const updateLiteral = createAction('UPDATE_LITERAL')
export const removeLiteral = createAction('REMOVE_LITERAL')
export const setMovingEdge = createAction('SET_MOVING_EDGE')
export const setActiveIds = createAction('SET_ACTIVE_IDS')
export const updateGraphParameters = createAction('UPDATE_GRAPH_PARAMETERS')
